// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIpOw45nHOwby3LvmFD0fHk0mH8yJdZhA',
    appId: '1:382193558514:web:659937d3678b635e9c416b',
    messagingSenderId: '382193558514',
    projectId: 'codelab3-38854',
    authDomain: 'codelab3-38854.firebaseapp.com',
    storageBucket: 'codelab3-38854.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5qUvna8RJnklT3GCDazggPrdUlFn8lQ',
    appId: '1:382193558514:android:ac6e80e70971e4789c416b',
    messagingSenderId: '382193558514',
    projectId: 'codelab3-38854',
    storageBucket: 'codelab3-38854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOxqpCt9ywdaLxtOtxF1C34DaKDB0_fE',
    appId: '1:382193558514:ios:9165f1e18f8bb30e9c416b',
    messagingSenderId: '382193558514',
    projectId: 'codelab3-38854',
    storageBucket: 'codelab3-38854.appspot.com',
    iosBundleId: 'com.example.codelab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAOxqpCt9ywdaLxtOtxF1C34DaKDB0_fE',
    appId: '1:382193558514:ios:9165f1e18f8bb30e9c416b',
    messagingSenderId: '382193558514',
    projectId: 'codelab3-38854',
    storageBucket: 'codelab3-38854.appspot.com',
    iosBundleId: 'com.example.codelab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIpOw45nHOwby3LvmFD0fHk0mH8yJdZhA',
    appId: '1:382193558514:web:6620dcdde8fb98cb9c416b',
    messagingSenderId: '382193558514',
    projectId: 'codelab3-38854',
    authDomain: 'codelab3-38854.firebaseapp.com',
    storageBucket: 'codelab3-38854.appspot.com',
  );
}
